<?php

$locations = [
    "Arizona",
    "Atlanta",
    "Austin",
    "Baltimore",
    "Bay Area",
    "Boston",
    "Charlotte",
    "Chicago",
    "Cincinnati",
    "Cleveland",
    "Colorado",
    "Columbus",
    "Connecticut",
    "D.C.",
    "Dallas",
    "Detroit",
    "Fort Worth",
    "Fresno",
    "Houston",
    "Indiana",
    "Jacksonville",
    "Knoxville",
    "Las Vegas",
    "Los Angeles",
    "Mexico City",
    "Miami-Ft Lauderdale",
    "Minnesota",
    "Nashville",
    "New Orleans",
    "New York",
    "Niagara",
    "Orlando",
    "Philadelphia",
    "Pittsburgh",
    "Portland",
    "Puerto Rico",
    "Raleigh-Durham",
    "Sacramento",
    "San Diego",
    "Seattle",
    "St. Louis",
    "Tampa Bay",
    "Toronto",
    "Upstate NY",
    "Vancouver",
    "Virginia",
    "Wisconsin"
];